### ISSUE TITLE
Random Once or Every Time

### ISSUE THREAD

**Issue by lld533** [eezkni/FDL#1]
Dear Dr. Ni,

Thanks for your nice work. I just figured out that in current implementation of FDL, all random variables used for projection are initialized only once in the __init__ function and the fixed random values are accordingly used in each call of forward_once function. I happened to notice that such variables are usually sampled every time for each projection in similar works such as [HSW](https://github.com/UT-Austin-Data-Science-Group/HSW/blob/main/functions.py). Could you please give me some suggestions on this point? Many thanks in advance.

**Comment by Chtholly17** [comment]
Hello, thank you very much for your interest in our work! 
Regarding the issue you mentioned about the initialization of projection random variables, we have experimented both two approaches: (1) initializing only once  in __init__, and (2) initializing at each forward pass. Both approaches showed similar performance, but (1) had a slight advantage. Therefore, we finally decided to adopt approach (1).
